### ISSUE TITLE
CIRI died because different read lengths

### ISSUE THREAD

**Issue by wdecoster** [smangul1/rop#100]
I really like the idea of your tool and I am eager to try it on my transcriptomics dataset. Nice work.

It took a while to trace the error, but I could find the log messages in the end telling me that the CIRI step died because the reads have different lengths. Is this something we have to take care of ourselves?

In addition, I first downloaded the script from sourceforge (according to the tutorial: wget https://sourceforge.net/projects/rop2/files/latest/download/rop.tar.gz) but this installation missed seqclean. Cloning git was alright.

Another remark is that the python code appears rather messy to me, could use some more functions instead of long code blocks. Smal functions doing limited things will keep code ordered, and make debugging and developing easy. Lastly, if you can avoid using os.sysem() that would be great, subprocess should cover all possibilities and simultaneously allow you to read error codes and act accordingly. In both problems (CIRI sizing and absence of seqclean) the os.system(cmd) just died and the script only discovered that after finding that the output was empty.

**Comment by smangul1** [comment]
Hi Wouter,

Thanks for the valuable feedback. What is the read length you have? I will check if CIRI can work on the variable length?

We are planning on the code improvement in the next release. We were thining to use Snakemake. 

Thanks,
Serghei

**Comment by wdecoster** [comment]
Hi Serghei,

I performed trimming on my data (containing poly A tails for example) so the lengths are anything between 25 and 140 nucleotides (with the majority above 120). 

I had a look at the ciri page on sourceforge and in the latest added readme file it is stated: "What's new in CIRI2? 
....
2. CIRI2 supports variable read lengths and can process combined data sets after trimming.
....
"

So probably CIRI2 might solve the problem?

Regards,
Wouter

**Comment by wdecoster** [comment]
Perhaps unrelated, but I would recommend using the shlex module for formatting your command for using subprocess.call. You can feed shlex.split the string you would execute on the command line without bothering about how to separate arguments.

**Comment by smangul1** [comment]
Thanks for all your helpfull  suggestions. Kevin and Linus to integrate you suggestion and update to CIRI2 into a new release coming soon. We will keep you posted. Serghei

**Comment by smangul1** [comment]
Hi Wouter,

We have pushed new release 1.0.5. We followed your suggestions to start improve the code. More improvements will come in the next release. CIRI2 should be also available in the next release. For now i suggest 2 options:
1) don't trim so the length will b ethe same 
2) run ROP with jobarray option, which will basically will run Step 1 and Step 2 and save after_step1_step2.fastq file which you can run manually through CIRI2

**Comment by wdecoster** [comment]
Dear Serghei,

Thanks for letting me know. I'll give it a try. I trimmed to remove polyA tails and polyG tails (because NextSeq sequencing was used). I think the second suggestion would be the most relevant.

Cheers,
Wouter
