### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by brianpenghe** [smangul1/rop#103]
1.0.4 got the following error message which was not there using 1.0.2:

Processing 4230025 unmapped reads of length 28
1. Quality Control...
--filtered 953514 low quality reads
Traceback (most recent call last):
  File "/woldlab/castor/home/phe/programs/rop-1.0.4/rop.py", line 626, in <module>
    nLowCReads=int(nLowCReadsTemp.rstrip().strip())
ValueError: invalid literal for int() with base 10: ''

Any thoughts?

**Comment by wdecoster** [comment]
Based on the error, nLowCReadsTemp is empty ("") which is invalid for `int()`. Putting a `print(nLowCReadsTemp) would prove that hypothesis.

I'm not sure what this step exactly should do and I have not time to look into the code, but wrapping this in a try-except block or first checking the variable might avoid this.

**Comment by smangul1** [comment]
Thanks for pointing this out! We will fix it in a 1.0.5 release and will let you know! Serghei

**Comment by smangul1** [comment]
Can you please try new release 1.0.5. I think the problem with invalid literal should disappear
