### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by smangul1** [smangul1/rop#109]
if i run 

python rop.py --skipPreliminary --microbiome --qsub example/unmappedExampleFasta.fasta test --f

i get this error
ERROR: Subprocess crashed. 
Traceback (most recent call last):
  File "rop.py", line 278, in <module>
    if subprocess.Popen([cmd], shell=True).wait(): raise SubprocessError()
rop_functions.SubprocessError

**Comment by kahsieh** [comment]
I was unable to reproduce the error using ROP v1.0.6. Have you checked the following?
- sufficient disk space
- install dependencies by running INSTALL.sh

**Comment by smangul1** [comment]
Thanks Kevin! You are right that was insufficient disk space
