### ISSUE TITLE
bug: incorrect files for running gprofile

### ISSUE THREAD

**Issue by brainfood** [smangul1/rop#111]
Hi ROP devs,

I've been attempting to run the gprofile script on the tutorial dataset (mappedReads_chr22.bam). When I run the gprofile script:
python gprofile.py mappedReads_chr22.bam mappedReads_chr22.csv

I get the following error:
Load gene annotations ...
Load ~/ROP_v1.0.6/source/gprofile/annotations/human/bedPrepared/UTR3_GRCh37_prepared.bed
Traceback (most recent call last):
  File "~/ROP_v1.0.6/gprofile.py", line 271, in <module>
    geneID=line[3]
IndexError: list index out of range

When I checked the UTR3_GRCh37_prepared.bed file included with the v1.0.6, it only contains 3 columns (here's the first few lines):
1,100155472,100155633
1,100159618,100160097
1,100174258,100174453
1,100174258,100174583
1,100176380,100176505

So it looks like the gprofile.py script is expecting bed files with some extra columns. I checked the README file in the ~/ROP_v1.0.6/source/gprofile/annotations/human/bedPrepared/ directory, I see these instructions:
python /u/home/s/serghei/code2/DumsterDivingRNASeq/scripts/prepareBed.py ../bedOriginal/UTR3_GRCh37.bed UTR3_GRCh37_prepared.bed h

However, these differ from the instructions on the wiki (https://github.com/smangul1/rop/wiki/How-to-prepare-gene-annotations-for-gprofile):
python ../../../scripts/prepareBed.py UTR3_NCBIM37_v2.bed genes_transcripts.txt ../bedPrepared/geneCoordinates_NCBIM37.bed ../bedPrepared/UTR3_NCBIM37_prepared.bed m

So the long and the short of this is I think the prepared bed files included with the v1.0.6 sourceforge build are from an older version. Any thoughts?

Thanks for your help.

**Comment by smangul1** [comment]
Thanks for noticing this. We are working now to fix it 
Thanks,
Serghei

**Comment by smangul1** [comment]
Unfortunally gprofile option has retired now! We suggest using subread package for classifying reads into genomics categories! Thanks, Serghei
