### ISSUE TITLE
can not download tutorial RNA-seq data

### ISSUE THREAD

**Issue by meganfrederick** [smangul1/rop#113]
I would like to use the rop, but can not download the data for the tutorial. 

$ wget https://googledrive.com/host/0B_NUyiE86yDwaUxoVjhlSjN5SkE/skinExample.tar
--2017-03-03 10:33:01--  https://googledrive.com/host/0B_NUyiE86yDwaUxoVjhlSjN5SkE/skinExample.tar
Resolving googledrive.com (googledrive.com)... 
216.58.217.161, 2607:f8b0:4004:80a::2001
Connecting to googledrive.com (googledrive.com)|216.58.217.161|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-03-03 10:33:06 ERROR 404: Not Found.

**Comment by kahsieh** [comment]
Hello,
The link you have is outdated. Please try running `$ gdrive download 0B_NUyiE86yDwdFFwZWFTck9QQjg` using the gdrive app (https://github.com/prasmussen/gdrive). @smangul1 I think some documentation needs to be updated?

**Comment by smangul1** [comment]
Thanks Kevin! yes. Let me give you the access to the tutorial so you can update ! Serghei

**Comment by smangul1** [comment]
@kahsieh Actually can you check if you can edit the tutorial?

**Comment by kahsieh** [comment]
I have updated the tutorial.
