### ISSUE TITLE
Megan Frederick

### ISSUE THREAD

**Issue by meganfrederick** [smangul1/rop#114]
Good Morning,

I installed ROP as described on your wiki page:
https://github.com/smangul1/rop/wiki/How-to-install-ROP%3F

However when I run rop with the mouse option I receive this message:
5. Lymphocyte profiling is skipped (not supported for mouse).

I see in the mouse database that the antibody database is present. Do I need to download a later version of rop for lymphocyte profiling?

**Comment by kahsieh** [comment]
Hello,
A new version of ImReP with mouse support is completed but still undergoing testing. It will be included with the next release of ROP.

**Comment by meganfrederick** [comment]
Fantastic! Thank you
