### ISSUE TITLE
rop and paired reads input files

### ISSUE THREAD

**Issue by meganfrederick** [smangul1/rop#115]
Good afternoon,

I am curious about input files. I see in the manuscript you carry out the rop using paired end samples, but the way I understand it, the input you provide is a single BAM or fastq file.

How does the rop handle these single files? Is the protocol considering each read separately or is it analyzing the input reads as pairs? Can the protocol accept two fastq files (mate1 and mate2) as input? 

I've asked a couple questions so far and really appreciate your time. 

Best,
Megan

**Comment by smangul1** [comment]
Hi Megan,

You are right the input is single reads. In case fo paired-end reads we will disregard the pairing information.  The ROP accept a single FASTQ file. In case you have 2 files, we recommend to concatenate them.  Let me know if you have more questions. Thanks, Serghei

**Comment by smangul1** [comment]
Hi Megan,

Please let me know if it works. Unless you have other questions, I will close the issue.

Sergehi

**Comment by meganfrederick** [comment]
Hi Serghei,

Yes, thank you very much. This answers my question

Best,
Megan
