### ISSUE TITLE
Exception when running rop-imrep.sh

### ISSUE THREAD

**Issue by PoslavskySV** [smangul1/rop#119]
Hi,

the following exception occurs when I try to process some data:

Processing 76968876 unmapped reads of length 100.
1. Quality Control...
--filtered 24 low quality reads
Traceback (most recent call last):
  File "/home/poslavsky/work/imrep/rop/rop.py", line 61, in <module>
    nReads["LowC"] = step_1b(unmapped_file)
  File "/home/poslavsky/work/imrep/rop/rop_functions.py", line 242, in step_1b
    return int(nLowCReadsTemp.strip())
ValueError: invalid literal for int() with base 10: ''

**Comment by PoslavskySV** [comment]
Is there a chance that this bug will be fixed soon?

Here is a complete list of commands that cause error behaviour (I have uploaded the bam file [here](https://drive.google.com/uc?export=download&confirm=L061&id=0ByRC0HN9SQScSU1NcUt5ckJZS2M) ):

	wget https://downloads.sourceforge.net/project/rop2/1.0.7/rop.tar.gz
	tar -xzf rop.tar.gz && rm rop.tar.gz
	cd rop
	python getDB.py .

	samtools index the_file.bam
	./rop-imrep.sh the_file.bam the_result ""

The full error output:

	ImReP is written by Igor Mandric and Serghei Mangul.

	Released under the terms of the General Public License version 3.0 (GPLv3)

	For more details see: https://sergheimangul.wordpress.com/rop/
	ROP Tutorial: https://github.com/smangul1/rop/wiki 
	********************************************************************************
	[M::bam2fq_mainloop] processed 4790 reads
	[main_samview] region "14:106032614-107288051" specifies an unknown reference name. Continue anyway.
	[M::bam2fq_mainloop] processed 0 reads
	[main_samview] region "2:89156874-89630436" specifies an unknown reference name. Continue anyway.
	[M::bam2fq_mainloop] processed 0 reads
	[main_samview] region "22:22380474-23265085" specifies an unknown reference name. Continue anyway.
	[M::bam2fq_mainloop] processed 0 reads
	[main_samview] region "14:22090057-23021075" specifies an unknown reference name. Continue anyway.
	[M::bam2fq_mainloop] processed 0 reads
	[main_samview] region "7:141998851-142510972" specifies an unknown reference name. Continue anyway.
	[M::bam2fq_mainloop] processed 0 reads
	[main_samview] region "7:38279625-38407656" specifies an unknown reference name. Continue anyway.
	[M::bam2fq_mainloop] processed 0 reads
	********************************************************************************
	ROP (v1.0.6) is a computational protocol aimed to discover the source of all reads, 
	originated from complex RNA molecules, recombinant B and T cell receptors and microbial
	communities. 

	Written by Serghei Mangul (smangul@ucla.edu), Harry Taegyun Yang 
	(harry2416@gmail.com), Kevin Hsieh (kevin.hsieh@ucla.edu), and Linus Chen 
	(u6.30cl@gmail.com). University of California, Los Angeles (UCLA). (c) 2016. 

	Released under the terms of the General Public License version 3.0 (GPLv3)

	For more details see: https://sergheimangul.wordpress.com/rop/
	ROP Tutorial: https://github.com/smangul1/rop/wiki 
	********************************************************************************
	Processing 4790 unmapped reads of length 50.
	1. Quality Control...
	--filtered 1 low quality reads
	Traceback (most recent call last):
	  File "/work/rnaSeqSimulation/test4/rop_sources/rop.py", line 61, in <module>
	    nReads["LowC"] = step_1b(unmapped_file)
	  File "/work/rnaSeqSimulation/test4/rop_sources/rop_functions.py", line 242, in step_1b
	    return int(nLowCReadsTemp.strip())
	ValueError: invalid literal for int() with base 10: ''


Here is my system configuration (Dockerfile):

	FROM ubuntu:16.04

	MAINTAINER maintainer

	USER root

	RUN apt-get update && apt-get install -yq --no-install-recommends \
	    build-essential \
	    ca-certificates \
	    libgmp3-dev git software-properties-common python-software-properties \
	    wget unzip zlib1g-dev python python-dev python-setuptools parallel samtools
	RUN easy_install pip
	RUN pip install pairwise biopython gmpy numpy pysam

**Comment by smangul1** [comment]
sorry for the delay. We are planning to have a new release by the end of the week. Thanks,
Serghei

**Comment by PoslavskySV** [comment]
Looking forward, thanks!
