### ISSUE TITLE
SAMTOOLS command not found

### ISSUE THREAD

**Issue by PoslavskySV** [smangul1/rop#120]
Script `rop-imrep.sh` is broken. When running ./rop-imrep.sh it fails with `SAMTOOLS command not found`. You need to replace "SAMTOOLS" with "$SAMTOOLS" in `rop-imrep.sh` (and `rop-imrepGRCh38.sh` as well) as it was suggested in pull request https://github.com/smangul1/rop/pull/117

**Comment by smangul1** [comment]
Thanks! We will push next release early next week . We will make sure to fix this problem. Thanks,
Serghei
