### ISSUE TITLE
New bug in rop-imrep.sh ...

### ISSUE THREAD

**Issue by PoslavskySV** [smangul1/rop#121]
When running:

    ./rop-imrep.sh some.bam some.output ""

the following error occurs:

    ./rop-imrep.sh: line 4: ./argparse.bash: No such file or directory
    ./rop-imrep.sh: line 5: argparse: command not found

I suppose lines 4-5 in `rop-imrep.sh` are incorrect.

**Comment by smangul1** [comment]
Hi, 
Sorry for delay with the answer. Please use imrep tool . Now it supports bam files with a mixture of mapped and unmapped reads. Please just use github clone to get a new version and read manual here : https://github.com/mandricigor/imrep/wiki/Run-ImReP-for-bams-(with--mapped-and-unmapped-reads)

**Comment by smangul1** [comment]
Let me know if you have any other questions. Otherwise i will close the issue
