### ISSUE TITLE
Update getDB.py and install.sh 

### ISSUE THREAD

**Issue by Toseph** [smangul1/rop#128]
The latest git clone as of 03/06/18 needs some modification to work out of the box. 

Changing the shebang in getDB.py to 
`#!/usr/bin/env python`
Will allow most python virtual environments to run properly instead of including a reference to a personal directory.  Or include a note in the install instructions to change this parameter before running the installer. 

In install.sh,  please make generic references to /tools/Miniconda-Install starting from line 74 or provide a way to pass an argument to this string using $1 as it can be confusing for those less familiar with these errors. 

You can include a snippet such as the below to check for passed parameters. 
```
# check for passed parameters.
if [ "$#" -ne 1 ]; then
  echo "Please pass the path to your miniconda or virtualenv python installation:"
  echo "this can be /usr/bin/python or the output of 'which python'"
  exit 1
fi
```

**Comment by kahsieh** [comment]
Please see #129
