### ISSUE TITLE
replace install.sh with environment.yaml

### ISSUE THREAD

**Issue by epruesse** [smangul1/rop#131]
rop uses conda anyway, so adding the bioconda channel allmost all requirements can be installed via conda directly:

environment.yml:
```
channels:
- bioconda
- conda-forge
dependencies:
- metaphlan2
- pysam
- biopython
- numpy
- networkx
- intervaltree
- jellyfish
-....
```
and 
```
conda env create -n rop -f environment.yml
```
suffices to get pretty much all of that.

I recommend specifying whether networkx 1 or 2 is needed though - they are incompatible.

**Comment by kahsieh** [comment]
Once #129 is merged, most dependencies will be installed through conda or bioconda, though a MiniConda installation script is used instead of an `environment.yml`.

**Comment by smangul1** [comment]
#129 was merged. Please try the new release of ROP!
