### ISSUE TITLE
Distribute ROP as a package

### ISSUE THREAD

**Issue by epruesse** [smangul1/rop#132]
If ROP was a package (i.e. something that has a setup.py and can install itself into proper paths),  chances of getting distributed via e.g. bioconda or pip would increase. Also, there wouldn't be any need to patch the python entry files with the correct interpreter path. That's done with `setup.py install` automatically by setuptools.

**Comment by kahsieh** [comment]
Once #129 is merged, ROP will have a single installer (`install.sh`) that takes care of everything, and ROP's python file no longer will no longer need to be patched with a shebang. Do you think that will suffice?

**Comment by smangul1** [comment]
#129 was merged. Please try a new release of ROP!

**Comment by kahsieh** [comment]
With #129 merged, the installation process is greatly simplified, but some more work is needed to distribute it via package manager(s).

**Comment by kahsieh** [comment]
https://github.com/bioconda/bioconda-recipes/pull/9765

**Comment by kahsieh** [comment]
ROP was added to bioconda on Sep 11, 2019
