### ISSUE TITLE
Enable ROP-mouse

### ISSUE THREAD

**Issue by igordot** [smangul1/rop#133]
By default, the `install.sh` script installs the human database. I am trying to add a non-human database. I tried running:
```
./install.sh -o mouse
```
That gave an error:
```
----- Downloading databases ----------------------------------------------------
Downloading item: BWAindex for mouse
Error: Unknown ORGANISM.
```

I also checked the wiki where the instructions are:
```
python getDB.py --organism mouse ~/
```
However, it seems that file does not exist anymore.

**Comment by smangul1** [comment]
Thanks for bringing this up! We will investigate this and will let you know. Thanks, Serghei

**Comment by kahsieh** [comment]
@smangul1 What is the status on the mouse database?

**Comment by smangul1** [comment]
ROP-mouse is ready. Please give a try! Serghei and Kevin

**Comment by igordot** [comment]
Is there a way to install a database without reinstalling everything from scratch? If you run `install.sh`, it will do the full install.

**Comment by kahsieh** [comment]
#137 changes the behavior so that ROP won't reinstall by default when downloading an additional database
