### ISSUE TITLE
Enable circrna and bacteria steps

### ISSUE THREAD

**Issue by kahsieh** [smangul1/rop#135]
The circrna and bacteria databases have been missing since v1.0.8. This should be addressed.

**Comment by smangul1** [comment]
I will am building bacteria database. As soon as this is done, we can make bacteria step optional. 
We will also make NCL step optional. I think it should be ready, just make sure to test it. It is taking a lot of time, so I suggest to make it optional. Serghei

**Comment by kahsieh** [comment]
The metaphlan database also appears to be broken now, so I'm disabling that step for now.

**Comment by InesdeSantiago** [comment]
Is metphlan dbase still broken? can you enable it now?

**Comment by smangul1** [comment]
Sorry for the delay! We are working on this now and expect the update by the end of the week!

**Comment by kahsieh** [comment]
Metaphlan has been re-enabled.

**Comment by InesdeSantiago** [comment]
Great! Thank you !

**Comment by david-a-siegel** [comment]
Is there something wrong with the original one?  Do you have a reference file we could use and call bwa-mem ourselves?

**Comment by kahsieh** [comment]
Could you try asking @smangul1? (See http://www.sergheimangul.com/ if he doesn't respond here)
