### ISSUE TITLE
Conda environment file with necessary packages

### ISSUE THREAD

**Issue by jaime11** [smangul1/rop#138]
Hello,

I am trying to install rop, thank you a lot for the software!
The issue is that I have conda installed already and the installer produces some errors due to pip and also tries to install miniconda. The server where I am trying to install the software doesn't have permission to write on certain areas (I can only write in my home directory). I am also reading from
https://github.com/smangul1/rop/wiki/How-to-install-ROP%3F

That the tool requires up to 50GB for some databases, so it would be necessary for my situation to be able to store this somewhere else since I don't have that amount of space in the drive.

Is it possible to export a conda environment file with the necessary packages to install to create a personalized environment to run the tool?

Thank you in advance

**Comment by smangul1** [comment]
Kevin, Can you please help here

Serghei

**Comment by kahsieh** [comment]
@jaime11 The installer tries to install MiniConda by default, but the installation is entirely within rop's directory, so you shouldn't run into permission errors with MiniConda. That said, it can be disabled using the `-n|--native` option. The installer also offers the `-d|--dbdest` option to change the location where the database is stored, so you can select a location with more space.

I have prepared an [environment.yml](https://github.com/kahsieh/rop/blob/master/tools/environment.yml) file. This should have everything needed for the conda environment.

**Comment by jaime11** [comment]
Thank you, I realized about that raised issue afterwards. Just to note, the yml file in "tools" gave a pip install error for the package suffix_tree-2.1.tar.gz:

IOError: [Errno 2] No such file or directory

Since the installation installs this package later, I removed the install from the environment.yml

**Comment by jaime11** [comment]
Note, as the environment.yml is now I am missing the package biopython

ImportError: No module named Bio
