### ISSUE TITLE
rop error message

### ISSUE THREAD

**Issue by fadista** [smangul1/rop#139]
Hi,

I have the following error when running the latest version of rop:
`Traceback (most recent call last):
  File "/home/projects/ssi_gen1/data/pregnancy/unmapped/rop/rop.py", line 197, in <module>
    nReads["NCL"] = step_4(unmapped_file, cmd)
  File "/home/projects/ssi_gen1/data/pregnancy/unmapped/rop/rop_functions.py", line 344, in step_4
    if subprocess.Popen([cmd], shell=True).wait(): raise SubprocessError()
rop_functions.SubprocessError`

Do you know what might be wrong? Thanks.

**Comment by smangul1** [comment]
Can you please send the command you are running

Serghei

**Comment by kahsieh** [comment]
Hi @fadista,

Please check that you are using the latest version and running `rop.sh`, not `rop.py` (additional details available in README.md).

**Comment by fadista** [comment]
The command was
`python /home/projects/ssi_gen1/data/pregnancy/unmapped/rop/rop.py --f /home/projects/ssi_gen1/data/pregnancy/unmapped/batch1/PINE_DEN15_01_GAGATTCC_ACGTCCTGUnmapped.out.mate1.fastq /home/projects/ssi_gen1/data/pregnancy/unmapped/batch1/PINE_DEN15_01_GAGATTCC_ACGTCCTGUnmapped.out.mate1`

**Comment by kahsieh** [comment]
Hi @fadista,

I can see that you're running `rop.py`, which doesn't exist in the latest version of ROP. Again, please check that you are using the latest version.

**Comment by fadista** [comment]
Hi @kahsieh 
Thanks, I am now running rop.sh on the newest version. Can I ask why circrna, metaphlan, and bacteria are not available in the current release? Thanks.

**Comment by kahsieh** [comment]
Hi @fadista,

Those three steps have been disabled due to database problems. @smangul1 will rebuild the circrna and bacteria databases, while the metaphlan issue will have to be addressed upstream.

**Comment by smangul1** [comment]
Hi @fadista,

We are planning to have the circrna  and bacteria steps ready in the next release. 

Thanks,
Serghei

**Comment by fadista** [comment]
Thanks. Do you know more or less when would the next release be out?

**Comment by smangul1** [comment]
we plan a new release in 2 weeks!

Serghei

**Comment by fadista** [comment]
Thanks. Can you notify me when it becomes available? Thanks

João
