### ISSUE TITLE
metaphlan outputs always 2 reads

### ISSUE THREAD

**Issue by InesdeSantiago** [smangul1/rop#143]
Hi 
All my metaphlan runs (> 200) output the same result in the tsv file, which is only 2 found reads and 100% unclassified 
:-( I dont know what is wrong, if my samples or ROP. Do you know what the expected output from the example rop file? If there is any metaphlan expected result with the example file, I can compare my run with expected output to see where the problem is..
thanks!

**Comment by smangul1** [comment]
What is the data? Which tissues? It is known metaphlan2 to suffer from low sensitivity. We have a method for viruses and fungi and protozoa, which we plan to integrate in ROP. For now, you can run it as a standalone application, in case you are interested. 


Serghei

**Comment by InesdeSantiago** [comment]
Ah I see.
It was in Melanoma. Is the method published and can i access it (is it
ready)? I can also wait,
thanks!
ines

**Comment by smangul1** [comment]
The tools is not published. but it is usable. 
https://github.com/smangul1/needle/wiki

Serghei

**Comment by InesdeSantiago** [comment]
thanks!

**Comment by kahsieh** [comment]
The example does output 2 reads, 100% unclassified for metaphlan, but I confirmed that the latest release identifies more reads on other samples. I think it is just low sensitivity, as @smangul1 said.
