### ISSUE TITLE
install.sh script not working 

### ISSUE THREAD

**Issue by BeckfordJay** [smangul1/rop#144]
I'm stuck with the installer. When I try to run the ./install.sh command from repository directory, it does not go through.
When I try to edit the code to resolve these issues, I receive more issues further down the code such as these. Are there any simple fixes? I'm using bash + OSX if this is of any help.
<img width="567" alt="screen shot 2019-02-20 at 5 53 51 pm" src="https://user-images.githubusercontent.com/42796660/53140495-d9dd5280-355a-11e9-80e0-785988150fbf.png">

<img width="742" alt="screen shot 2019-02-20 at 10 01 10 pm" src="https://user-images.githubusercontent.com/42796660/53140550-0d1fe180-355b-11e9-869e-995fdf57e1a4.png">

<img width="579" alt="screen shot 2019-02-20 at 10 01 49 pm" src="https://user-images.githubusercontent.com/42796660/53140577-2759bf80-355b-11e9-86b7-e095d424df07.png">

**Comment by BeckfordJay** [comment]
Bash + Homebrew + OSX***

**Comment by kahsieh** [comment]
Hi @BeckfordJay, unfortunately we don't support ROP on Mac shell because utilities such as `readlink` function differently than on Linux. It might be possible to run ROP (hackily) on Mac with the help GNU Coreutils, but we would recommend just running it with Linux.

**Comment by BeckfordJay** [comment]
I see. Thanks for the heads up!
