### ISSUE TITLE
Mouse rDNA profiling fails: samtools sort: failed to read header from "-"

### ISSUE THREAD

**Issue by borshago** [smangul1/rop#145]
Hi,

I'm trying to run rop on the example fastq file and get the following error:

> Processing 2503 unmapped reads. The first unmapped read has length 79.
> 1. Low quality read marking (-s lowq)...
> --> Skipped low quality read marking.
> 2. rDNA profiling (-s rdna)...
> samtools sort: failed to read header from "-"

The logfile example--02_rdna.log says the following:

> (ERR): ".../rop-master/db_mouse/ribosomal.DNA/ribosomal.DNA" does not exist or is not a Bowtie 2 index
> Exiting now ...

The contents of the rDNA database folder rop-master/db_mouse/ribosomal.DNA look like the files prepared for BWA alignment. How to get around this?

**Comment by kahsieh** [comment]
I was able to reproduce the error, though it doesn't seem to affect the other steps. There seems to be an issue with the contents of `db_mouse/ribosomal.DNA`. Could @smangul1 please check the format of that directory?

@borshago If this error crashes the program on your system, I would recommend skipping the rDNA step using the `-s` option for now.

**Comment by borshago** [comment]
I prepared a bowtie2 index named ribosomal.DNA in db_mouse/ribosomal.DNA using the example from the human database and the problem was solved.
