### ISSUE TITLE
Installation aborts when downloading MetaPhlAn2

### ISSUE THREAD

**Issue by Juliane-W** [smangul1/rop#146]
Hello, I'm trying to install ROP with running the ./install.sh, but it aborts at the stage of downloading MetaPhlAn2:

![image](https://user-images.githubusercontent.com/46549848/113748361-4d715800-9700-11eb-94c3-d4d5ddd84778.png)

Linux version 4.15.0-136-generic
Python 3.8.8
biopython  1.78

Any suggestions how to solve this issue?

**Comment by kahsieh** [comment]
It looks like MetaPhlAn2 changed its location from https://bitbucket.org/biobakery/metaphlan2 to https://github.com/biobakery/metaphlan2, and Miniconda changed its location from https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh to http://repo.anaconda.com/miniconda/Miniconda-latest-Linux-x86_64.sh. I can patch it over the weekend.

**Comment by kahsieh** [comment]
Patched! Thanks for the report.
