### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by rgarcia27** [smangul1/rop#147]
Hi, 
I just installed ROP. I think I did it okay because I set up the environment and I could installed it without any warning or errors. The only thing I did different is that I installed Suffix Tree outside the .yml but with the tar.gz that comes in the repository. 

The problem is that I'm trying to run the examples and I can't because of this error that I honestly don't know how to fix. 
rop.sh: line 200: syntax error near unexpected token `>'

Please help.
Thanks!

**Comment by kahsieh** [comment]
Are you running ROP on Linux?

**Comment by rgarcia27** [comment]
yes I am

**Comment by kahsieh** [comment]
It sounds like ROP isn't compatible with your shell. Could you try using the latest version of bash?

**Comment by rgarcia27** [comment]
Looks like there's a problem with the server but I could installed successfully on another one. 
Thanks a lot!

**Comment by rgarcia27** [comment]
Hi, sorry, I could installed correctly but I have the same error. The bash version of the new server is 4.4.20, what version do I need?

Thanks!

**Comment by kahsieh** [comment]
That version of bash should be able to run ROP. I'd suggest checking your shell options to make sure process redirection is allowed. For example, you might have to disable POSIX mode (`set +o posix`).
