### ISSUE TITLE
BWAindex for human and mouse no longer available on google docs?

### ISSUE THREAD

**Issue by maaskola** [smangul1/rop#148]
Hi,

trying to install rop, I get 404 errors trying to download the files from google docs.
Are they still available?

This is the command constructed for downloading the human index:
```
curl --silent --insecure --cookie-jar cookies.txt             "https://docs.google.com/uc?export=download&id=19Uscw8KrPyUiuPcErrXpyOxN0PqUtbOZ"             | sed -rn 's .*confirm=([0-9A-Za-z_]+).* \1\n p\'
```

And this is the command constructed for the mouse index:
```
curl --silent --insecure --cookie-jar cookies.txt             "https://docs.google.com/uc?export=download&id=17g26AzgYhvpY5J5Spofs_rVwXVgVxtrL"             | sed -rn 's .*confirm=([0-9A-Za-z_]+).* \1\n p\'
```

Trying to visit either of these URLs leads to a 404 error page.

Could you please check if these files are still available, or make them available again if they aren't anymore?

Thanks and all the best!

**Comment by kahsieh** [comment]
I updated the database locations. Please note that this project is overall unmaintained and uses Python 2, which is past end-of-life, so you may encounter other issues.
