### ISSUE TITLE
getopt issue

### ISSUE THREAD

**Issue by drayac** [smangul1/rop#149]
Hi all, 

I am trying to launch the installation but I directly get an error from getopt, saying

 --
Error: Environment doesn't support getopt.

Although I installed it via "brew install gnu-getopt" command, and the getopt command seems to be working. Is that the correct getopt ? Of note: I work from a MacosX, M3 machine. 

Cheers,

A. Coudray

**Comment by kahsieh** [comment]
Hi @drayac, please take a look at #144.
