### ISSUE TITLE
Regarding Input fastq file 

### ISSUE THREAD

**Issue by NitinMandloi** [smangul1/rop#37]
Hi,

    Should I align my RNA sequencing reads first to human hg19 reference genome using any aligner and then extract the unaligned reads and give as input to rop or I can directly give full fastq file to rop and rop will take care about unaligned reads???

Thank you

Regards

**Comment by smangul1** [comment]
Hi Nitin,

You would need to align  the reads first . And prepare the unmapped
reads either in bam or fastq format

Please also keep the mapped reads (bam) as we can use those to profile
the constant regions of antobodies

I will follow up shorty wit the new release and manual for the ROP tool

Thanks,
Serfghei

**Comment by harrydgnt** [comment]
New release is available as well as detailed instruction in the wiki!
