### ISSUE TITLE
Master Script

### ISSUE THREAD

**Issue by harrydgnt** [smangul1/rop#51]
Add Master script that would wrap all the scripts generated with qsubarray option 

It is currently set to run it non-reductively in order to make it parallelizable. 

For other users who would be interested in reductive way, This step is essential

**Comment by harrydgnt** [comment]
Add function so the script would write logs in the log file when used with qsub or qsubarray option?

**Comment by smangul1** [comment]
It is a great point let's do in release 1.04. Serghei
