### ISSUE TITLE
 --microbiome --skipPreliminary

### ISSUE THREAD

**Issue by smangul1** [smangul1/rop#58]
--microbiome --skipPreliminary

those 2 options does not work properly

input for microbiome is fastq but supposed to be fasta

**Comment by harrydgnt** [comment]
I think it is already fasta? 

What is the problem exactly?

**Comment by smangul1** [comment]
the problem is that is we choose skipPreliminary fastq is not converted to
fasta and fastq is passed to microbiome analysis

how gtex and cancer are downloading?
I will be in the lab tmrw around 2pm

Serghei






On Wed, May 18, 2016 at 4:36 PM, Harry Taegyun Yang <
notifications@github.com> wrote:

> I think it is already fasta?
>
> What is the problem exactly?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/smangul1/rop/issues/58#issuecomment-220189221>
>



-- 
Sincerely,
Serghei Mangul, Ph.D
QCB Postdoctoral Fellow,
Institute for Quantitative and Computational Biosciences,
Department of Computer Science and Human Genetics
University of California, Los Angeles
http://serghei.bioinformatics.ucla.edu/

**Comment by harrydgnt** [comment]
The download is going well. The cancer is pretty slow I guess. I downloaded
about 300 bams now, which is about 1/4 of the total samples.

I will look into it definitely.

2016-05-18 20:12 GMT-07:00 Serghei Mangul <notifications@github.com>:

> the problem is that is we choose skipPreliminary fastq is not converted to
> fasta and fastq is passed to microbiome analysis
>
> how gtex and cancer are downloading?
> I will be in the lab tmrw around 2pm
>
> Serghei
>
>
>
>
>
>
> On Wed, May 18, 2016 at 4:36 PM, Harry Taegyun Yang <
> notifications@github.com> wrote:
>
> > I think it is already fasta?
> >
> > What is the problem exactly?
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/smangul1/rop/issues/58#issuecomment-220189221>
> >
>
>
>
> --
> Sincerely,
> Serghei Mangul, Ph.D
> QCB Postdoctoral Fellow,
> Institute for Quantitative and Computational Biosciences,
> Department of Computer Science and Human Genetics
> University of California, Los Angeles
> http://serghei.bioinformatics.ucla.edu/
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/smangul1/rop/issues/58#issuecomment-220217411>
>



-- 
Harry (Taegyun) Yang
Physiological Science, Biochemistry. B.S.
University of California Los Angeles, Class of 2015.
Student Researcher, Zarlab, Department of Computer Science, UCLA
President, UCLA Korean Athletic Network

**Comment by smangul1** [comment]
i am visiting UCSF next week

On Monday i am meeting Elad

it would be great to have some preliminary results

Can you please run those 300 samples on Roel account now for immune only

Do you know how many cases and hoe many controls there are among those 300?

Serghei

On Wed, May 18, 2016 at 10:27 PM, Harry Taegyun Yang <
notifications@github.com> wrote:

> The download is going well. The cancer is pretty slow I guess. I downloaded
> about 300 bams now, which is about 1/4 of the total samples.
>
> I will look into it definitely.
>
> 2016-05-18 20:12 GMT-07:00 Serghei Mangul <notifications@github.com>:
>
> > the problem is that is we choose skipPreliminary fastq is not converted
> to
> > fasta and fastq is passed to microbiome analysis
> >
> > how gtex and cancer are downloading?
> > I will be in the lab tmrw around 2pm
> >
> > Serghei
> >
> >
> >
> >
> >
> >
> > On Wed, May 18, 2016 at 4:36 PM, Harry Taegyun Yang <
> > notifications@github.com> wrote:
> >
> > > I think it is already fasta?
> > >
> > > What is the problem exactly?
> > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/smangul1/rop/issues/58#issuecomment-220189221>
> > >
> >
> >
> >
> > --
> > Sincerely,
> > Serghei Mangul, Ph.D
> > QCB Postdoctoral Fellow,
> > Institute for Quantitative and Computational Biosciences,
> > Department of Computer Science and Human Genetics
> > University of California, Los Angeles
> > http://serghei.bioinformatics.ucla.edu/
> >
> > —
> > You are receiving this because you were assigned.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/smangul1/rop/issues/58#issuecomment-220217411>
> >
>
>
>
> --
> Harry (Taegyun) Yang
> Physiological Science, Biochemistry. B.S.
> University of California Los Angeles, Class of 2015.
> Student Researcher, Zarlab, Department of Computer Science, UCLA
> President, UCLA Korean Athletic Network
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/smangul1/rop/issues/58#issuecomment-220230827>
>



-- 
Sincerely,
Serghei Mangul, Ph.D
QCB Postdoctoral Fellow,
Institute for Quantitative and Computational Biosciences,
Department of Computer Science and Human Genetics
University of California, Los Angeles
http://serghei.bioinformatics.ucla.edu/

**Comment by harrydgnt** [comment]
​I don't think there is control. I will look it up after debugging rop. I
think the problem is not only for microbiome but for the human filtering
step.

The output fasta file is not fasta but rather some weird binary file.

​

2016-05-18 22:33 GMT-07:00 Serghei Mangul <notifications@github.com>:

> i am visiting UCSF next week
>
> On Monday i am meeting Elad
>
> it would be great to have some preliminary results
>
> Can you please run those 300 samples on Roel account now for immune only
>
> Do you know how many cases and hoe many controls there are among those 300?
>
> Serghei
>
> On Wed, May 18, 2016 at 10:27 PM, Harry Taegyun Yang <
> notifications@github.com> wrote:
>
> > The download is going well. The cancer is pretty slow I guess. I
> downloaded
> > about 300 bams now, which is about 1/4 of the total samples.
> >
> > I will look into it definitely.
> >
> > 2016-05-18 20:12 GMT-07:00 Serghei Mangul <notifications@github.com>:
> >
> > > the problem is that is we choose skipPreliminary fastq is not converted
> > to
> > > fasta and fastq is passed to microbiome analysis
> > >
> > > how gtex and cancer are downloading?
> > > I will be in the lab tmrw around 2pm
> > >
> > > Serghei
> > >
> > >
> > >
> > >
> > >
> > >
> > > On Wed, May 18, 2016 at 4:36 PM, Harry Taegyun Yang <
> > > notifications@github.com> wrote:
> > >
> > > > I think it is already fasta?
> > > >
> > > > What is the problem exactly?
> > > >
> > > > —
> > > > You are receiving this because you authored the thread.
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/smangul1/rop/issues/58#issuecomment-220189221>
> > > >
> > >
> > >
> > >
> > > --
> > > Sincerely,
> > > Serghei Mangul, Ph.D
> > > QCB Postdoctoral Fellow,
> > > Institute for Quantitative and Computational Biosciences,
> > > Department of Computer Science and Human Genetics
> > > University of California, Los Angeles
> > > http://serghei.bioinformatics.ucla.edu/
> > >
> > > —
> > > You are receiving this because you were assigned.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/smangul1/rop/issues/58#issuecomment-220217411>
> > >
> >
> >
> >
> > --
> > Harry (Taegyun) Yang
> > Physiological Science, Biochemistry. B.S.
> > University of California Los Angeles, Class of 2015.
> > Student Researcher, Zarlab, Department of Computer Science, UCLA
> > President, UCLA Korean Athletic Network
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/smangul1/rop/issues/58#issuecomment-220230827>
> >
>
>
>
> --
> Sincerely,
> Serghei Mangul, Ph.D
> QCB Postdoctoral Fellow,
> Institute for Quantitative and Computational Biosciences,
> Department of Computer Science and Human Genetics
> University of California, Los Angeles
> http://serghei.bioinformatics.ucla.edu/
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/smangul1/rop/issues/58#issuecomment-220231595>
>



-- 
Harry (Taegyun) Yang
Physiological Science, Biochemistry. B.S.
University of California Los Angeles, Class of 2015.
Student Researcher, Zarlab, Department of Computer Science, UCLA
President, UCLA Korean Athletic Network

**Comment by smangul1** [comment]
Can you just take those 300 samples and send them to roel account  for
immune now. this way we can expect some results by Friday



On Wed, May 18, 2016 at 10:39 PM, Harry Taegyun Yang <
notifications@github.com> wrote:

> ​I don't think there is control. I will look it up after debugging rop. I
> think the problem is not only for microbiome but for the human filtering
> step.
>
> The output fasta file is not fasta but rather some weird binary file.
>
>
> ​
>
> 2016-05-18 22:33 GMT-07:00 Serghei Mangul <notifications@github.com>:
>
> > i am visiting UCSF next week
> >
> > On Monday i am meeting Elad
> >
> > it would be great to have some preliminary results
> >
> > Can you please run those 300 samples on Roel account now for immune only
> >
> > Do you know how many cases and hoe many controls there are among those
> 300?
> >
> > Serghei
> >
> > On Wed, May 18, 2016 at 10:27 PM, Harry Taegyun Yang <
> > notifications@github.com> wrote:
> >
> > > The download is going well. The cancer is pretty slow I guess. I
> > downloaded
> > > about 300 bams now, which is about 1/4 of the total samples.
> > >
> > > I will look into it definitely.
> > >
> > > 2016-05-18 20:12 GMT-07:00 Serghei Mangul <notifications@github.com>:
> > >
> > > > the problem is that is we choose skipPreliminary fastq is not
> converted
> > > to
> > > > fasta and fastq is passed to microbiome analysis
> > > >
> > > > how gtex and cancer are downloading?
> > > > I will be in the lab tmrw around 2pm
> > > >
> > > > Serghei
> > > >
> > > >
> > > >
> > > >
> > > >
> > > >
> > > > On Wed, May 18, 2016 at 4:36 PM, Harry Taegyun Yang <
> > > > notifications@github.com> wrote:
> > > >
> > > > > I think it is already fasta?
> > > > >
> > > > > What is the problem exactly?
> > > > >
> > > > > —
> > > > > You are receiving this because you authored the thread.
> > > > > Reply to this email directly or view it on GitHub
> > > > > <https://github.com/smangul1/rop/issues/58#issuecomment-220189221>
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Sincerely,
> > > > Serghei Mangul, Ph.D
> > > > QCB Postdoctoral Fellow,
> > > > Institute for Quantitative and Computational Biosciences,
> > > > Department of Computer Science and Human Genetics
> > > > University of California, Los Angeles
> > > > http://serghei.bioinformatics.ucla.edu/
> > > >
> > > > —
> > > > You are receiving this because you were assigned.
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/smangul1/rop/issues/58#issuecomment-220217411>
> > > >
> > >
> > >
> > >
> > > --
> > > Harry (Taegyun) Yang
> > > Physiological Science, Biochemistry. B.S.
> > > University of California Los Angeles, Class of 2015.
> > > Student Researcher, Zarlab, Department of Computer Science, UCLA
> > > President, UCLA Korean Athletic Network
> > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/smangul1/rop/issues/58#issuecomment-220230827>
> > >
> >
> >
> >
> > --
> > Sincerely,
> > Serghei Mangul, Ph.D
> > QCB Postdoctoral Fellow,
> > Institute for Quantitative and Computational Biosciences,
> > Department of Computer Science and Human Genetics
> > University of California, Los Angeles
> > http://serghei.bioinformatics.ucla.edu/
> >
> > —
> > You are receiving this because you were assigned.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/smangul1/rop/issues/58#issuecomment-220231595>
>
> >
>
>
>
> --
> Harry (Taegyun) Yang
> Physiological Science, Biochemistry. B.S.
> University of California Los Angeles, Class of 2015.
> Student Researcher, Zarlab, Department of Computer Science, UCLA
> President, UCLA Korean Athletic Network
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/smangul1/rop/issues/58#issuecomment-220232277>
>



-- 
Sincerely,
Serghei Mangul, Ph.D
QCB Postdoctoral Fellow,
Institute for Quantitative and Computational Biosciences,
Department of Computer Science and Human Genetics
University of California, Los Angeles
http://serghei.bioinformatics.ucla.edu/

**Comment by harrydgnt** [comment]
Fixed and Checked.
