### ISSUE TITLE
metahpan doesn't work 

### ISSUE THREAD

**Issue by smangul1** [smangul1/rop#70]
python /u/home/s/serghei/code2/rop/tools/metaphlan2.py /u/home/s/serghei/code2/rop/example/metaphlan/lostHumanReads/unmappedExample_after_rRNA_lostHuman.fasta /u/home/s/serghei/code2/rop/example/metaphlan/microbiomeProfile//metaphlan/unmappedExample_metaphlan.map --mpl_pkl /u/home/s/serghei/code2/rop/db/metaphlan/mpa_v20_m200.pkl --input_type multifasta --bowtie2db /u/home/s/serghei/code2/rop/db/metaphlan/mpa_v20_m200 -t reads_map --nproc 8 --bowtie2out /u/home/s/serghei/code2/rop/example/metaphlan/microbiomeProfile//metaphlan/unmappedExample_bowtie2out.txt
python /u/home/s/serghei/code2/rop/tools/metaphlan2.py --mpl_pkl /u/home/s/serghei/code2/rop/db/metaphlan/mpa_v20_m200.pkl --input_type bowtie2out /u/home/s/serghei/code2/rop/example/metaphlan/microbiomeProfile//metaphlan/unmappedExample_bowtie2out.txt -t rel_ab > /u/home/s/serghei/code2/rop/example/metaphlan/microbiomeProfile//metaphlan/unmappedExample_metaphlan_output.tsv
----------------
Warning! Biom python library not detected!
 Exporting to biom format will not work!
usage: metaphlan2.py --mpa_pkl MPA_PKL --input_type
                     {fastq,fasta,multifasta,multifastq,bowtie2out,sam}
                     [--bowtie2db METAPHLAN_BOWTIE2_DB]
                     [--bt2_ps BowTie2 presets] [--bowtie2_exe BOWTIE2_EXE]
                     [--bowtie2out FILE_NAME] [--no_map] [--tmp_dir]
                     [--tax_lev TAXONOMIC_LEVEL] [--min_cu_len]
                     [--min_alignment_len] [--ignore_viruses]
                     [--ignore_eukaryotes] [--ignore_bacteria]
                     [--ignore_archaea] [--stat_q]
                     [--ignore_markers IGNORE_MARKERS] [--avoid_disqm]
                     [--stat] [-t ANALYSIS TYPE] [--nreads NUMBER_OF_READS]
                     [--pres_th PRESENCE_THRESHOLD] [--clade] [--min_ab] [-h]
                     [-o output file] [--sample_id_key name]
                     [--sample_id value] [-s sam_output_file]
                     [--biom biom_output] [--mdelim mdelim] [--nproc N] [-v]
                     [INPUT_FILE] [OUTPUT_FILE]
metaphlan2.py: error: argument --mpa_pkl is required
Warning! Biom python library not detected!

**Comment by harrydgnt** [comment]
It works now.
