### ISSUE TITLE
Minor point on INSTALL Python dependency

### ISSUE THREAD

**Issue by npklein** [smangul1/rop#80]
In the INSTALL instructions it says "The ROP comes with no pre-requirements except Python". This does not work for Python 3+, which is quick to find out but still might consider to change it to "The ROP comes with no pre-requirements except Python 2.x".

**Comment by smangul1** [comment]
Thanks!!! we will update this information

**Comment by smangul1** [comment]
it was updated. ROP requires Python 2.7. Serghei 
The new release is available at https://sourceforge.net/projects/rop2/files/1.03/
