### ISSUE TITLE
using --skipQC tag throws error 

### ISSUE THREAD

**Issue by apatil1** [smangul1/rop#81]
If I use the skipQC tag the program tries to remove the original input fastq file (line 590 rop.py) and the program terminates.

`os.remove(afterrRNAFasta)`

**Comment by harrydgnt** [comment]
Hello! 

Can you let me know which version of rop you are using (i.e. 1.0.2)?

Thank you very much!

**Comment by apatil1** [comment]
I am using v1.0..2

**Comment by harrydgnt** [comment]
Alright it is fixed and the new release is gonna be released soon! I will let you know when it is available.

**Comment by smangul1** [comment]
The issue has been fix. Please see new release (to be available on Monday) 1.0.3
