### ISSUE TITLE
Adding sequence information to the output file for TCR/BCR

### ISSUE THREAD

**Issue by apatil1** [smangul1/rop#82]
Can you please add the qseq and sseq (sequence that is mapped by igblast) to output file? This is very useful information.

`-outfmt \"7 std qseq sseq\" `

**Comment by harrydgnt** [comment]
We will look into it and add it on future releases!

**Comment by apatil1** [comment]
I already made this update on the version I am running. If you are interested I will be happy to send you a pull request.

**Comment by smangul1** [comment]
Thanks for the comment Ashwini!

We will do it in our weekly release on Monday.

This will be the output 

V	reversed|HWI-ST0860:216:1:1101:2596:1987:0:1#AGTCAA	IGHV3-13*01	92.31	13	1	0	0	23	35	255	267	   15	19.0	GAGAGCCGGCGAC	GAGAGCCGGGGAC

**Comment by smangul1** [comment]
The issue has been fix. Please see new release (to be available on Monday) 1.0.3

**Comment by smangul1** [comment]
The new release is available at https://sourceforge.net/projects/rop2/files/1.03/
