### ISSUE TITLE
The tarball for installation contains broken symlinks

### ISSUE THREAD

**Issue by npklein** [smangul1/rop#84]
Directories in https://github.com/smangul1/rop/archive/1.0.2.tar.gz contain broken symlinks, e.g.
NPK@MacBook-Pro-van-NPK:~/Downloads/rop-1.0.2$ ls -l db/test/microbiome/bacteria/
total 352
lrwxr-xr-x@ 1 NPK  staff    50B 31 May 01:27 bacteria.00.idx@ -> /u/home/s/serghei/project/Bacteria/bacteria.00.idx
lrwxr-xr-x@ 1 NPK  staff    50B 31 May 01:27 bacteria.00.nhd@ -> /u/home/s/serghei/project/Bacteria/bacteria.00.nhd
lrwxr-xr-x@ 1 NPK  staff    50B 31 May 01:27 bacteria.00.nhi@ -> /u/home/s/serghei/project/Bacteria/bacteria.00.nhi

**Comment by harrydgnt** [comment]
Hello

Thank you for your suggestion. The symlinks are for our developmental use and it should be replaced if you run install.py with standard option, by overwriting the symlink files with actual database files. 

Let me know if there is a problem in installation step! 

Thank you.

**Comment by npklein** [comment]
We are using EasyBuild to install, a software build and installation framework for installing software. This tries to copy over the files before running install.py, which is what breaks the installation.

**Comment by smangul1** [comment]
we are planning to have a new release tomorrow and will try to fix those issues! Serghei

**Comment by harrydgnt** [comment]
Although I am not familiar with the easybuild system, our new installation, which will be included in the new release soon, should be able to fix it according to your description. We will definitely let you know when the new release is available!

**Comment by npklein** [comment]
Great, thanks!

**Comment by smangul1** [comment]
This issue has been fixed in new release. The new release is available at https://sourceforge.net/projects/rop2/files/1.03/
