### ISSUE TITLE
--jobArray and skipPreliminary doesn't work 

### ISSUE THREAD

**Issue by smangul1** [smangul1/rop#87]
while read line ; do python /u/home/s/serghei//collab/code/rop/rop.py --qsubArray --skipPreliminary $PWD/data/${line}.fastq $PWD//ropBrain/${line} ;done<1.sample

**Comment by harrydgnt** [comment]
What is the problem? Can you show me an example/

**Comment by harrydgnt** [comment]
I am not sure what the problem is. It just doesnt work?

**Comment by smangul1** [comment]
Let me check again and i will let you know
