### ISSUE TITLE
reads do not map to IGK rop v1.0.1/2

### ISSUE THREAD

**Issue by guerauF** [smangul1/rop#88]
In script rop.py (line 729) os.system(cmd) has to be added so the link to internal_data folder is created. This issue is in v1.0.1 as well as in v1.0.2.

**Comment by smangul1** [comment]
Thanks for pointing this. We are working to fix it and will include it in the weekly release on Monday

Thanks,
Serghei

**Comment by smangul1** [comment]
The issue has been fix in new release 1.0.3

**Comment by smangul1** [comment]
The new release is available at https://sourceforge.net/projects/rop2/files/1.03/
