### ISSUE TITLE
--fastqGz doesn't work

### ISSUE THREAD

**Issue by smangul1** [smangul1/rop#90]
fasta file is not correct

unmappedExample_gzip.fastq_after_lostRepeat.fasta

>CBBB@@BBBAA@CBB4=<@<BB;A<?ABA;B?7?>A;B@@@@<@BAA?6AB==@<<@A:A@@9<A>@=@===@=-@4?
@SRR1146076.56325TCACCATGACCAGGGACACGTCCACGAGCACAGTGTACATGGA
CCTGAGTAGTCTGAAATCTGAGGACACGGCCGTGTA+AABBBBBABA@?@?AA?@=A?AA
A>====?>??4@8B=?==?=?6<?8=8==6=?=?6===88===8=66784666<55@SRR
1146076.9989891ATCCCCCATGCCCCCACCCCACCACAAGAGGCAGCAGGCCCCAGG
CATAACACCTGTCTCTTCCACGTGCCCGTAGACG+B-<@/)>+;+;AA<3B118@@5=+0
=@9=0;6))%4B(.8@######################################@SRR11
46076.9989894CACGCGCCGGCCCCGTTGCCCCCGCGCGCGCGCACACTCGCGCGCCC
CGGCGACACGCAAATGAGCTGGCTACAGTGCC+=A@@B?B=<?@9AA78=/A>B9<'?;<
99##################################################@SRR1146
076.9989902CCACATGATGTGAGGCATCAGACCCACACTGTCAGCCCAGCAGGCCGGG

**Comment by harrydgnt** [comment]
alright something mustve gone wrong. 

Can you give me the command?
