### ISSUE TITLE
bam to fastq

### ISSUE THREAD

**Issue by guerauF** [smangul1/rop#96]
When the input is a bam file and converting to fastq it does not find the shared libbamtools.so.2.3.0 from bamtools.

**Comment by smangul1** [comment]
Let me have a look and check what i the issues. If you want a fast solution please install bamtools 

Thanks,
Serghei

**Comment by guerauF** [comment]
Yep, that's what I did.
Thanks!

**Comment by smangul1** [comment]
Harry, Can you take care of this?

**Comment by harrydgnt** [comment]
I think what Serghei meant was to use bamtools or bedtools bam2fastq for conversion rather than converting it through ROP, while we look into it. 

There is a problem with importing bam files right now. I am on it right now and I will let you know as soon as it is fixed

**Comment by smangul1** [comment]
Please try new release 1.0.5 the issue with bam file conversion was fixed. Thanks, Serghei
