### ISSUE TITLE
antibody diversity and alphaGeneral.py 

### ISSUE THREAD

**Issue by guerauF** [smangul1/rop#99]
How can I determine immunoglobulin diversity? For alphaGeneral.py input of column 2 has to be a float and using the exmple it points to the name of the sequence. Also, rop.1.0.3 output is tab delimited and alphaGeneral.py line 71  reader=csv.reader(f) should be changed to  reader=csv.reader(f, delimiter="\t").

**Comment by smangul1** [comment]
Let me look into the issue. I will keep you updated . Serghei

**Comment by guerauF** [comment]
The input has to be the output of rop from igblastn or it has to be summarized?
Thanks.

**Comment by guerauF** [comment]
Got it! I have to use a summarized file.
Thanks for all!

**Comment by smangul1** [comment]
great! Let me know if you have any other issues. We are currently working on the software to replace the igblast, which should infer more reliably the CDJ recombinations and infer CDR3. Serghei
